### ISSUE TITLE
Mention users?

### ISSUE THREAD

**Issue by andrewcartwright1** [jammerware/margiebot#19]
Hi,

In my project I'm replacing Jira usernames with Slack usernames and attempting to mention that user in the bots response, however when the bot responds its just plain text despite @andrew.cartwright being in the bots response.

Is there a way to make the bot mention these users?

**Comment by jammerware** [comment]
Hey Andrew,

In order to make the text of the bot's reply actually mention the user with
an actual link, you have to do a little special formatting when you're
composing the bot's reply. The official Slack API describes this here:
https://api.slack.com/docs/message-formatting#linking_to_channels_and_users

Margiebot's User model lets you do this kind of formatting easily. I did it
one of the example responders, actually - you can see that here:
https://github.com/jammerware/margiebot/blob/master/MargieBot.SampleResponders/src/Responders/ScoreResponder.cs

Let me know if you have any more questions.

**Comment by andrewcartwright1** [comment]
Got it, thanks :)
