### ISSUE TITLE
Is this Dead?

### ISSUE THREAD

**Issue by say25** [jammerware/margiebot#28]
This project hasn't been updated in a long time, is it dead?

**Comment by jammerware** [comment]
Only sort of. I haven't updated Margiebot for awhile because I'm doing a lot less .NET these days due to work. 

However, the (possibly) good news is that I've rebirthed it as a Node.js project. While this is pretty unhelpful for people who are strictly .NET, the Node version is more flexible (it works with Slack and Discord right out of the box, and you can add your own adapters for other platforms if there's one you're passionate about) and easier to get started with.

I'm still writing documentation, and it's missing a few features that Margiebot has, but check out the successor [here](https://github.com/jammerware/nargiebot).

**Comment by jammerware** [comment]
oh yeah - and while I'm building the documentation, you can see a working example in the new repo [here](https://github.com/jammerware/nargiebot/blob/9396aee3f9b56798cf03d66c401c9071e627f9f8/test/test.api-surface.ts)
