### ISSUE TITLE
Add support for setting the typing indicator

### ISSUE THREAD

**Issue by tonymobster** [jammerware/margiebot#3]
It would be great if Margie could set the typing indicator. "Giving users some instant feedback really helps reassure them when the bot is taking some time to respond, such as when making API calls or doing some processing that takes a few seconds." - [Building an intelligent bot](http://nordicapis.com/building-an-intelligent-bot-using-the-slack-api/)

[Wit.ai](https://wit.ai/) integration wouldn't be bad either ;)

Great library, the best and most fun I've worked with so far! Lemme know if I can be of assistance.

**Comment by jammerware** [comment]
Good idea. I'll look into this. Thanks for your feedback, and thanks for trying Margiebot out!

**Comment by chriscore** [comment]
Thanks for an excellent slack bot library :) This would be a great idea, perhaps having the bot set the typing indicator whilst running the GetResponse method on the responder would make sense?

**Comment by jammerware** [comment]
Yeah, this is a great idea, and something I'd like to do. I'm deep in the process of porting MargieBot to .NET Core 1.0.0, and I'll see if I can tackle this while I'm about it. Thanks for the kind words and the feedback!

**Comment by jammerware** [comment]
I'm still stabilizing the port to .NET Core, but the new version does automatically indicate that the bot is typing while a responder is being evaluated and provides API access to set the typing indicator (check it out [here](https://github.com/jammerware/margiebot/blob/a8b017a42cb2beca41558eb635076012b9645c1c/MargieBot/src/Bot.cs#L355)).

Stability issues seem to be affecting use of MargieBot with the WPF host app (MargieBot.UI), but otherwise things seem pretty decent after the port. If you're in a situation where you can experiment, I'd suggest updating your MargieBot ref to 2.0.4 or greater if you want to try out the typing indicator.

Thanks for your patience!
